---
language: python

python:
  - "2.7"

install:
  - pip install ansible

script:
  - ANSIBLE_ROLES_PATH=../ ansible-playbook --syntax-check -i tests/inventory tests/test.yml

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
