---
- name: Install required system packages
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

- name: Add a key to the list of trusted keys
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present
    update_cache: yes
    filename: 'docker-ce'

- name: Install packages
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
  - docker-ce

- name: Create SystemD directory for unit file customization
  file:
      group: root
      mode: 0755
      owner: root
      path: "/etc/systemd/system/{{docker_service_name}}.service.d"
      state: directory

- name: Configure SystemD unit file
  template:
    src: "{{ansible_distribution}}-{{ansible_distribution_major_version}}/docker.conf"
    dest: /etc/systemd/system/{{docker_service_name}}.service.d/docker.conf
    group: root
    mode: 0644
    owner: root
  register: docker_systemd_unit_file
  notify: Restart Docker service

- name: Reload SystemD
  command: systemctl daemon-reload
  when: docker_systemd_unit_file.changed
